// Configuración SEO global
const SITE = {
  url: 'https://mytoolhub.pages.dev',
  name: 'ToolHub',
  defaultTitle: 'ToolHub — +50 herramientas online gratuitas',
  defaultDesc: '+50 microherramientas online: conversores, calculadoras, generadores, tests de hardware y red. Gratis, sin registros y sin instalar nada.',
};

// Catálogo de herramientas
const TOOLS = [
  // ===== CONVERSORES =====
  { id:'length',      cat:'converters', name:'Longitud',          desc:'Metros, pies, millas, pulgadas…',   icon:'ruler',   ready:true },
  { id:'weight',      cat:'converters', name:'Peso',              desc:'Kilos, libras, onzas, toneladas',   icon:'weight',  ready:true },
  { id:'temperature', cat:'converters', name:'Temperatura',       desc:'Celsius, Fahrenheit, Kelvin',       icon:'temp',    ready:true },
  { id:'volume',      cat:'converters', name:'Volumen',           desc:'Litros, galones, mililitros',       icon:'beaker',  ready:true },
  { id:'area',        cat:'converters', name:'Área',              desc:'m², ft², acres, hectáreas',         icon:'square',  ready:true },
  { id:'speed',       cat:'converters', name:'Velocidad',         desc:'km/h, mph, m/s, nudos',             icon:'gauge',   ready:true },
  { id:'time',        cat:'converters', name:'Tiempo',            desc:'Segundos, horas, días, años',       icon:'clock',   ready:true },
  { id:'data',        cat:'converters', name:'Datos digitales',   desc:'KB, MB, GB, TB, bits',              icon:'data',    ready:true },
  { id:'energy',      cat:'converters', name:'Energía',           desc:'Joules, calorías, kWh',             icon:'bolt',    ready:true },
  { id:'pressure',    cat:'converters', name:'Presión',           desc:'Pa, bar, psi, atm',                 icon:'gauge',   ready:true },
  { id:'angle',       cat:'converters', name:'Ángulos',           desc:'Grados, radianes, gradianes',       icon:'angle',   ready:true },
  { id:'currency',    cat:'converters', name:'Divisas',           desc:'EUR, USD, GBP y más (live)',        icon:'coin',    ready:true },
  { id:'numbase',     cat:'converters', name:'Bases numéricas',   desc:'Binario, octal, decimal, hex',      icon:'binary',  ready:true },
  { id:'roman',       cat:'converters', name:'Números romanos',   desc:'Decimal ⇄ Romano',                  icon:'roman',   ready:true },

  // ===== CALCULADORAS =====
  { id:'mortgage',    cat:'calculators', name:'Hipoteca',         desc:'Cuota mensual y total de intereses', icon:'home',   ready:true },
  { id:'loan',        cat:'calculators', name:'Préstamo',         desc:'Calcula la cuota de cualquier préstamo', icon:'tax', ready:true },
  { id:'compound',    cat:'calculators', name:'Interés compuesto',desc:'Cuánto crecerá tu inversión',       icon:'coin',    ready:true },
  { id:'bmi',         cat:'calculators', name:'IMC',              desc:'Índice de masa corporal',           icon:'bmi',     ready:true },
  { id:'calories',    cat:'calculators', name:'Calorías (TMB)',   desc:'Calorías diarias que necesitas',    icon:'food',    ready:true },
  { id:'tip',         cat:'calculators', name:'Propina',          desc:'Reparte propinas y cuentas',        icon:'coin',    ready:true },
  { id:'percent',     cat:'calculators', name:'Porcentajes',      desc:'%, descuentos, aumentos',           icon:'percent', ready:true },
  { id:'age',         cat:'calculators', name:'Edad exacta',      desc:'Años, meses y días vividos',        icon:'clock',   ready:true },
  { id:'datediff',    cat:'calculators', name:'Días entre fechas',desc:'Diferencia entre dos fechas',       icon:'clock',   ready:true },
  { id:'discount',    cat:'calculators', name:'Descuento',        desc:'Precio final tras descuento',       icon:'percent', ready:true },
  { id:'irpf',        cat:'calculators', name:'IRPF España',      desc:'Estimación impuesto sobre la renta', icon:'tax',    ready:true },

  // ===== GENERADORES =====
  { id:'password',    cat:'generators',  name:'Contraseñas',      desc:'Seguras y aleatorias',              icon:'key',     ready:true },
  { id:'uuid',        cat:'generators',  name:'UUID v4',          desc:'Identificadores únicos',            icon:'binary',  ready:true },
  { id:'qr',          cat:'generators',  name:'Códigos QR',       desc:'Genera QR de cualquier texto/URL',  icon:'qr',      ready:true },
  { id:'lorem',       cat:'generators',  name:'Lorem Ipsum',      desc:'Texto de relleno',                  icon:'text',    ready:true },
  { id:'random',      cat:'generators',  name:'Número aleatorio', desc:'Entre dos valores',                 icon:'binary',  ready:true },
  { id:'hash',        cat:'generators',  name:'Hash SHA',         desc:'SHA-1, SHA-256, SHA-512',           icon:'key',     ready:true },
  { id:'palette',     cat:'generators',  name:'Paleta de colores',desc:'Combinaciones armoniosas',          icon:'palette', ready:true },

  // ===== TEXTO =====
  { id:'wordcount',   cat:'text',        name:'Contador de palabras', desc:'Palabras, caracteres, líneas',  icon:'count',   ready:true },
  { id:'case',        cat:'text',        name:'Cambiar mayúsculas',   desc:'UPPER, lower, Title Case',      icon:'case',    ready:true },
  { id:'slug',        cat:'text',        name:'Slug URL',         desc:'Convierte texto a slug',            icon:'text',    ready:true },
  { id:'reverse',     cat:'text',        name:'Invertir texto',   desc:'Da la vuelta a cualquier texto',    icon:'case',    ready:true },
  { id:'base64',      cat:'text',        name:'Base64',           desc:'Codifica y decodifica Base64',      icon:'binary',  ready:true },
  { id:'urlcode',     cat:'text',        name:'URL encode',       desc:'Codifica y decodifica URLs',        icon:'binary',  ready:true },
  { id:'json',        cat:'text',        name:'Formateador JSON', desc:'Embellece y valida JSON',           icon:'binary',  ready:true },

  // ===== COLOR =====
  { id:'colorconv',   cat:'color',       name:'Color HEX/RGB/HSL',desc:'Convierte entre formatos',          icon:'palette', ready:true },
  { id:'colorpicker', cat:'color',       name:'Selector de color',desc:'Pick visual y códigos',             icon:'palette', ready:true },

  // ===== RED / INFO =====
  { id:'myip',        cat:'network',     name:'¿Cuál es mi IP?',  desc:'IP pública y ubicación',            icon:'globe',   ready:true },
  { id:'browserinfo', cat:'network',     name:'Info navegador',   desc:'User agent, sistema, resolución',   icon:'monitor', ready:true },
  { id:'speedtest',   cat:'network',     name:'Test de velocidad',desc:'Descarga estimada (Mbps)',          icon:'gauge',   ready:true },

  // ===== HARDWARE =====
  { id:'monitorhz',   cat:'hardware',    name:'Hz del monitor',   desc:'Mide la tasa de refresco real',     icon:'monitor', ready:true },
  { id:'mousehz',     cat:'hardware',    name:'Hz del ratón',     desc:'Polling rate del mouse',            icon:'mouse',   ready:true },
  { id:'cps',         cat:'hardware',    name:'Clicks por segundo',desc:'Test CPS',                         icon:'mouse',   ready:true },
  { id:'reaction',    cat:'hardware',    name:'Tiempo de reacción',desc:'Mide tus reflejos',                icon:'bolt',    ready:true },
  { id:'dpi',         cat:'hardware',    name:'Calculadora DPI',  desc:'Convierte sensibilidad entre DPIs', icon:'mouse',   ready:true },

  // ===== TIEMPO =====
  { id:'stopwatch',   cat:'time',        name:'Cronómetro',       desc:'Con vueltas',                       icon:'clock',   ready:true },
  { id:'timer',       cat:'time',        name:'Temporizador',     desc:'Cuenta atrás con alarma',           icon:'clock',   ready:true },
  { id:'worldclock',  cat:'time',        name:'Reloj mundial',    desc:'Hora en varias ciudades',           icon:'globe',   ready:true },
  { id:'pomodoro',    cat:'time',        name:'Pomodoro',         desc:'25 min trabajo / 5 descanso',       icon:'clock',   ready:true },

  // ===== PREMIUM / PRÓXIMAMENTE =====
  { id:'pdfmerge',    cat:'files',       name:'Unir PDFs',        desc:'Combina varios PDFs en uno',        icon:'file',    ready:false, premium:true },
  { id:'imgresize',   cat:'files',       name:'Redimensionar imagen', desc:'Cambia tamaño sin perder calidad', icon:'image', ready:false },
  { id:'imgconvert',  cat:'files',       name:'Convertir imagen', desc:'PNG, JPG, WEBP, AVIF',              icon:'image',   ready:false, premium:true },
  { id:'bgremove',    cat:'files',       name:'Quitar fondo',     desc:'Elimina el fondo de imágenes',      icon:'image',   ready:false, premium:true },
];

// Slugs SEO-friendly y metadata extendido por herramienta.
// Cada entry: [slug, title (para <title> y H1), description, keywords]
const TOOL_SEO = {
  length:      ['conversor-longitud',      'Conversor de longitud (metros, pies, millas…)',         'Convierte metros, kilómetros, pies, pulgadas, millas, yardas, millas náuticas y más. Instantáneo y gratis.'],
  weight:      ['conversor-peso',          'Conversor de peso (kg, libras, onzas)',                 'Convierte kilogramos, gramos, libras, onzas, toneladas y stones al instante.'],
  temperature: ['conversor-temperatura',   'Conversor de temperatura (°C, °F, K)',                  'Convierte grados Celsius, Fahrenheit y Kelvin online. Rápido y exacto.'],
  volume:      ['conversor-volumen',       'Conversor de volumen (litros, galones, ml)',            'Convierte litros, mililitros, galones US/UK, tazas, cucharadas, pintas y más.'],
  area:        ['conversor-area',          'Conversor de área (m², acres, hectáreas)',              'Convierte metros cuadrados, hectáreas, acres, pies cuadrados y más.'],
  speed:       ['conversor-velocidad',     'Conversor de velocidad (km/h, mph, m/s)',               'Convierte km/h, mph, m/s, nudos y pies por segundo.'],
  time:        ['conversor-tiempo',        'Conversor de tiempo (segundos, horas, días)',           'Convierte segundos, minutos, horas, días, semanas, meses y años.'],
  data:        ['conversor-datos',         'Conversor de datos (KB, MB, GB, TB)',                   'Convierte bits, bytes, KB, MB, GB, TB y PB al instante.'],
  energy:      ['conversor-energia',       'Conversor de energía (J, kWh, calorías)',               'Convierte joules, kilojoules, calorías, kilocalorías, watt-hora y kWh.'],
  pressure:    ['conversor-presion',       'Conversor de presión (bar, psi, atm)',                  'Convierte pascales, bar, atmósferas, PSI y mmHg.'],
  angle:       ['conversor-angulos',       'Conversor de ángulos (grados, radianes)',               'Convierte grados, radianes, gradianes y vueltas.'],
  currency:    ['conversor-divisas',       'Conversor de divisas EUR USD GBP en tiempo real',       'Convierte euros, dólares, libras y más de 15 divisas con tasas actualizadas en tiempo real.'],
  numbase:     ['conversor-bases',         'Conversor de bases numéricas (binario, hex, decimal)',  'Convierte entre binario, octal, decimal y hexadecimal. Ideal para programadores.'],
  roman:       ['numeros-romanos',         'Conversor de números romanos',                          'Convierte cualquier número decimal a número romano y viceversa (1–3999).'],
  mortgage:    ['calculadora-hipoteca',    'Calculadora de hipoteca online gratis',                 'Calcula tu cuota mensual de hipoteca, el total a pagar y los intereses. Tipo fijo.'],
  loan:        ['calculadora-prestamo',    'Calculadora de préstamo',                               'Calcula la cuota de cualquier préstamo personal: intereses, cuota mensual y total.'],
  compound:    ['interes-compuesto',       'Calculadora de interés compuesto',                      'Calcula cuánto crecerá tu inversión con aportaciones periódicas y interés compuesto.'],
  bmi:         ['calculadora-imc',         'Calculadora de IMC (Índice de Masa Corporal)',          'Calcula tu IMC y descubre si tienes peso normal, sobrepeso u obesidad.'],
  calories:    ['calorias-diarias',        'Calculadora de calorías diarias (TMB)',                 'Calcula tu tasa metabólica basal y las calorías que necesitas según tu actividad.'],
  tip:         ['calculadora-propina',     'Calculadora de propina y división de cuenta',           'Calcula la propina y reparte la cuenta entre varios comensales.'],
  percent:     ['calculadora-porcentajes', 'Calculadora de porcentajes',                            'Calcula porcentajes, descuentos, aumentos y variaciones porcentuales.'],
  age:         ['calculadora-edad',        'Calculadora de edad exacta',                            'Calcula tu edad exacta en años, meses, días, horas y minutos vividos.'],
  datediff:    ['dias-entre-fechas',       'Calcular días entre dos fechas',                        'Calcula la diferencia entre dos fechas en años, meses, días, horas y minutos.'],
  discount:    ['calculadora-descuento',   'Calculadora de descuento y precio final',               'Calcula cuánto ahorras y el precio final tras aplicar un descuento.'],
  irpf:        ['calculadora-irpf',        'Calculadora de IRPF España',                            'Estimación del IRPF estatal por tramos. Calcula tu sueldo neto anual y mensual.'],
  password:    ['generador-contrasenas',   'Generador de contraseñas seguras',                      'Genera contraseñas seguras y aleatorias con mayúsculas, números y símbolos. 100% local.'],
  uuid:        ['generador-uuid',          'Generador de UUID v4',                                  'Genera identificadores únicos universales (UUID v4) al instante.'],
  qr:          ['generador-qr',            'Generador de códigos QR online gratis',                 'Crea códigos QR de cualquier texto, URL o número de teléfono. Descarga PNG gratis.'],
  lorem:       ['generador-lorem-ipsum',   'Generador de Lorem Ipsum',                              'Genera texto de relleno Lorem Ipsum: párrafos, frases o palabras.'],
  random:      ['numero-aleatorio',        'Generador de números aleatorios',                       'Genera un número aleatorio entre dos valores.'],
  hash:        ['generador-hash-sha',      'Generador de hash SHA-1, SHA-256, SHA-512',             'Calcula el hash SHA-1, SHA-256, SHA-384 o SHA-512 de cualquier texto. 100% local.'],
  palette:     ['generador-paleta-colores','Generador de paleta de colores',                        'Crea paletas armoniosas: monocromática, complementaria, triádica o análoga.'],
  wordcount:   ['contador-palabras',       'Contador de palabras y caracteres',                     'Cuenta palabras, caracteres, frases, líneas y tiempo de lectura de cualquier texto.'],
  case:        ['cambiar-mayusculas',      'Convertir mayúsculas y minúsculas',                     'Cambia un texto a MAYÚSCULAS, minúsculas, Título, camelCase, snake_case o kebab-case.'],
  slug:        ['generador-slug',          'Generador de slug para URLs',                           'Convierte cualquier texto en un slug limpio para URLs (sin tildes ni espacios).'],
  reverse:     ['invertir-texto',          'Invertir texto online',                                 'Invierte caracteres, palabras o líneas de cualquier texto.'],
  base64:      ['codificar-base64',        'Codificar y decodificar Base64',                        'Codifica o decodifica cualquier texto en Base64. 100% local.'],
  urlcode:     ['url-encode-decode',       'Codificar y decodificar URLs',                          'Encode/decode de URLs y parámetros para usar caracteres especiales.'],
  json:        ['formatear-json',          'Formateador y validador de JSON',                       'Embellece, minifica y valida cualquier JSON. Detecta errores de sintaxis.'],
  colorconv:   ['conversor-color-hex-rgb', 'Conversor de color HEX, RGB, HSL, CMYK',                'Convierte códigos de color entre HEX, RGB, HSL, HSV y CMYK.'],
  colorpicker: ['selector-color',          'Selector de color (color picker)',                      'Pick visual y obtén el código en HEX, RGB y HSL.'],
  myip:        ['cual-es-mi-ip',           '¿Cuál es mi IP? Información de ubicación',              'Descubre tu IP pública, ubicación aproximada, ISP, país y zona horaria.'],
  browserinfo: ['info-navegador',          'Información de mi navegador y dispositivo',             'User agent, sistema operativo, pantalla, CPU, RAM y más datos de tu dispositivo.'],
  speedtest:   ['test-velocidad-internet', 'Test de velocidad de internet',                         'Mide la velocidad de descarga de tu conexión a internet en Mbps.'],
  monitorhz:   ['hz-monitor',              'Test de Hz del monitor (refresh rate)',                 'Mide la tasa de refresco real de tu monitor (60, 120, 144, 240 Hz…).'],
  mousehz:     ['hz-raton-polling-rate',   'Test de polling rate del ratón (Hz)',                   'Mide los Hz reales (polling rate) de tu ratón. Ideal para gaming.'],
  cps:         ['test-cps-clicks',         'Test de CPS (clicks por segundo)',                      'Mide cuántos clicks por segundo eres capaz de hacer en 10 segundos.'],
  reaction:    ['test-tiempo-reaccion',    'Test de tiempo de reacción',                            'Mide tu tiempo de reacción en milisegundos. Reta a tus reflejos.'],
  dpi:         ['calculadora-dpi-sensibilidad','Calculadora de DPI y sensibilidad',                 'Convierte tu sensibilidad de juego entre distintos DPIs manteniendo el mismo eDPI.'],
  stopwatch:   ['cronometro-online',       'Cronómetro online con vueltas',                         'Cronómetro online con sistema de vueltas. Preciso y fácil de usar.'],
  timer:       ['temporizador-online',     'Temporizador online con alarma',                        'Configura un temporizador con cuenta atrás y alarma sonora.'],
  worldclock:  ['reloj-mundial',           'Reloj mundial (hora en varias ciudades)',               'Consulta la hora actual en Madrid, Londres, Nueva York, Tokio y más ciudades.'],
  pomodoro:    ['pomodoro-online',         'Temporizador Pomodoro online',                          'Técnica Pomodoro: 25 min de trabajo y 5 min de descanso. Para concentrarte mejor.'],
  pdfmerge:    ['unir-pdf',                'Unir varios PDFs en uno',                               'Combina varios archivos PDF en uno solo. Sin marcas de agua.'],
  imgresize:   ['redimensionar-imagen',    'Redimensionar imagen online',                           'Cambia el tamaño de imágenes sin perder calidad.'],
  imgconvert:  ['convertir-imagen',        'Convertir imagen PNG, JPG, WEBP, AVIF',                 'Convierte imágenes entre PNG, JPG, WEBP y AVIF.'],
  bgremove:    ['quitar-fondo-imagen',     'Quitar fondo de imagen automáticamente',                'Elimina el fondo de cualquier imagen con IA. Resultado en PNG transparente.'],
};

// Reverse lookup slug → tool id
const SLUG_TO_ID = Object.fromEntries(Object.entries(TOOL_SEO).map(([id,[slug]]) => [slug, id]));

const CATEGORIES = {
  all:        { name:'Todas',        icon:'all'        },
  converters: { name:'Conversores',  icon:'ruler'      },
  calculators:{ name:'Calculadoras', icon:'percent'    },
  generators: { name:'Generadores',  icon:'key'        },
  text:       { name:'Texto',        icon:'text'       },
  color:      { name:'Color',        icon:'palette'    },
  network:    { name:'Red',          icon:'globe'      },
  hardware:   { name:'Hardware',     icon:'monitor'    },
  time:       { name:'Tiempo',       icon:'clock'      },
  files:      { name:'Archivos',     icon:'file'       },
};

const ICONS = {
  ruler: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M21.3 8.7 8.7 21.3a2.4 2.4 0 0 1-3.4-3.4L17.9 5.3a2.4 2.4 0 0 1 3.4 3.4Z"/><path d="m7.5 10.5 2 2M10.5 7.5l2 2M13.5 4.5l2 2M4.5 13.5l2 2"/></svg>',
  weight:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="5" r="3"/><path d="M6.5 8h11l1.9 11.4a2 2 0 0 1-2 2.6h-10.8a2 2 0 0 1-2-2.6Z"/></svg>',
  temp:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M14 4v10.5a4 4 0 1 1-4 0V4a2 2 0 1 1 4 0Z"/></svg>',
  beaker:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M5 3h14M6 3v15a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V3M6 14h12"/></svg>',
  square:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>',
  gauge: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M12 14 8 10M3.4 14a9 9 0 1 1 17.2 0"/></svg>',
  clock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
  data:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg>',
  bolt:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M13 2 4 14h7l-1 8 9-12h-7l1-8Z"/></svg>',
  angle: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M4 20h16L4 4v16ZM10 20a6 6 0 0 0-6-6"/></svg>',
  coin:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="12" r="9"/><path d="M15 9.5a3 3 0 0 0-3-1.5c-1.7 0-3 1-3 2.2s1 1.8 3 2.3 3 1 3 2.3-1.3 2.2-3 2.2a3 3 0 0 1-3-1.5M12 6v2M12 16v2"/></svg>',
  binary:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="4" y="3" width="6" height="8" rx="1"/><rect x="14" y="13" width="6" height="8" rx="1"/><path d="M4 13h6v8M14 3h6v8"/></svg>',
  roman: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M4 5h6M4 19h6M7 5v14M14 5l3 14M20 5l-3 14"/></svg>',
  home:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="m3 11 9-8 9 8M5 10v10h14V10"/></svg>',
  tax:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>',
  bmi:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="5" r="2"/><path d="M12 7v6M8 21l4-8 4 8M9 13h6"/></svg>',
  food:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M12 3a6 6 0 0 0-6 6c0 2 1 4 2 6l1 6h6l1-6c1-2 2-4 2-6a6 6 0 0 0-6-6Z"/></svg>',
  qr:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><path d="M14 14h3v3h-3zM20 14v3M14 20h3M20 20v1"/></svg>',
  key:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M16 7l3 3"/></svg>',
  text:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M4 6h16M4 12h16M4 18h10"/></svg>',
  count: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M4 6h10M4 12h16M4 18h7M18 4v8M22 8h-8"/></svg>',
  case:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M3 18 8 6l5 12M5 14h6M14 18h4a3 3 0 0 0 0-6h-4Z"/></svg>',
  percent:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M19 5 5 19"/><circle cx="7" cy="7" r="2.5"/><circle cx="17" cy="17" r="2.5"/></svg>',
  palette:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M12 22a10 10 0 1 1 10-10c0 2.5-2 4-4 4h-2a2 2 0 0 0-2 2 2 2 0 0 1-2 4"/><circle cx="7" cy="12" r="1.2"/><circle cx="9.5" cy="7.5" r="1.2"/><circle cx="14.5" cy="7.5" r="1.2"/><circle cx="17" cy="12" r="1.2"/></svg>',
  globe: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></svg>',
  monitor:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
  mouse: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 6v4"/></svg>',
  file:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/></svg>',
  image: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-5-5L5 21"/></svg>',
  all:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',
};
